### ISSUE TITLE
Set AMOUNT as a HORIZONTAL SCROLL VIEW to avoid breakline numbers

### ISSUE THREAD

**Issue by ManoelPradoMark22** [Daniel-Vinicius/cryptocontrol#3]
I'm a Ignite (Rocketseat) student too :) Sou Brasileiro 

Option 1: See my commit when I made that change: https://github.com/ManoelPradoMark22/ignite_reactNative_gofinances_project2/commit/c5a97e6d742cb7a370c2e992e363561995c215f3

Option 2: And, also when I improve using a amazing lib:
https://github.com/ManoelPradoMark22/ignite_reactNative_gofinances_project2/commit/0f629037a04547345e2125f0b66491c655199f60
Video showing the change with the TextTicker lib: 
https://www.youtube.com/watch?v=Ev1_tT98kDI&ab_channel=ManoeldeOliveiraPradoNeto

But, For the Option 2 works 100% fine (for the Amount can be grabbed and dragged manually), you must to fork the lib and make a little change (I explain in the video the problem) and use your forkedLib:
https://github.com/deanhet/react-native-text-ticker/pull/112/commits/c88ae39ced5efdbab1027b2fb3d8ce62176c13fe
https://github.com/ManoelPradoMark22/react-native-text-ticker

If you liked the option 2 (I loved) and if you discover a way to fixed without use the react-native-gesture-handler, please, tell me. Because I already openned a pullrequest in the oficial llib but they replied that it is not possible to made my change in the oficial lib. The answer: https://github.com/deanhet/react-native-text-ticker/pull/112#issuecomment-957298981

Look how your HighlightCard breaks the application when the Amount is too big:
![Screenshot_20211102-155051_Crypto Control.jpg](https://user-images.githubusercontent.com/53825592/139927064-9ba8ffef-478d-41df-bb17-c6e8bd84d988.jpg) 

The Option 1 or Option2 fix that problem (I liked the option 2 most)

Hugs man, nice work.

**Comment by Daniel-Vinicius** [comment]
Perfeito nem tinha percebido isso abre um PR com a opção 2 que eu aprovo.

Perfect had not even realized this opens a 
PR with option 2 that I approve.

**Comment by ManoelPradoMark22** [comment]
> Perfeito nem tinha percebido isso abre um PR com a opção 2 que eu aprovo.
> 
> Perfect had not even realized this opens a PR with option 2 that I approve.

Perfeito, acabei de fazer o PR:
https://github.com/Daniel-Vinicius/cryptocontrol/pull/4/commits/fb3ae4e995c635387ddd2f37d4dd537cfbb8440c

Dá uma testada pra ver se tá tudo ok, pq não consegui rodar o seu projeto aqui pra teste (mesmo antes de fazer as alterações). Ficava acusando 'main has not been registered', tanto no emulador quanto no dispositivo físico.
Mas segui direitinho o que eu fiz no meu, então tudo indica que vai funcionar ok.
Eu adicionei a biblioteca react-native-text-ticker pelo meu fork, que ja vem com a alteracao que eu fiz para usar o ScrollView do react native gesture handler. Caso eu adicionasse direto pela biblioteca ao inves do meu fork, nao seria possivel ter o arrasto manual do amount no highlightcard, como explicado no vídeo:
https://www.youtube.com/watch?v=Ev1_tT98kDI&ab_channel=ManoeldeOliveiraPradoNeto
Dá uma conferida no PR, se tiver tudo ok manda bala. Valeu meu caro, fica com Deus.

**Comment by Daniel-Vinicius** [comment]
@ManoelPradoMark22 nesse erro na hora de rodar o projeto você tentou rodar com expo start?
Porque se sim aí é por isso, esse projeto usa WatermelowDB e aí não dá pra rodar com expo start.
Mas se não, aí não sei porque na minha máquina tá funcionando.

**Comment by ManoelPradoMark22** [comment]
> @ManoelPradoMark22 nesse erro na hora de rodar o projeto você tentou rodar com expo start?
> Porque se sim aí é por isso, esse projeto usa WatermelowDB e aí não dá pra rodar com expo start.
> Mas se não, aí não sei porque na minha máquina tá funcionando.

Ss, tentei com o expo. Mas depois tentei com o yarn android também.  Não entendi pq nao rodou. 
Tenta clonar o seu repositório em outra pasta p conferir, em seguida dá o yarn no projeto e depois o yarn android p ver se roda de boas.
